apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.6.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: requester-backend
  name: requester-backend
spec:
  ports:
  - name: "8081"
    port: 80
    targetPort: 8081
  selector:
    io.kompose.service: requester-backend
  type: LoadBalancer
status:
  loadBalancer: {}
